### ISSUE TITLE
Issue with library initialization and HMI boot command (0x0000)

### ISSUE THREAD

**Issue by czagrzebski** [STONElibrary/stone_serial#1]
When the Stone Serial Arduino Library is first initialized, it crashes when it receives the boot command (0x0000) from the HMI. If I initialize the Stone library and send any other command, then it works fine. After sending an initial command from the HMI (other than 0x0000) and then reboot the display (not the Arduino), then the 0x0000 command is received properly. I unfortunately cannot debug the issue further, but I believe it is an issue with the initialization of the library. 

I am using the latest version of the library (0.07) on the STM32-based Arduino Portenta H7.

**Comment by STONElibrary** [comment]
There is a problem with the updated version of arduino library, the IDE shows the downloaded v1.0.8, but it should actually be v1.0.6. I am working on this problem, you can download the example of the latest 1.0.8 version from the main repository. If you still have the problem, please describe your problem in detail and send a screenshot to my email 445029416@qq.com
